CARGAR LOS 3 DATASETS

In [4]:
import pandas as pd

demo = pd.read_csv("df_final_demo.csv")
web_data_pt_1 = pd.read_csv("df_final_web_data_pt_1.csv") 
web_data_pt_2 = pd.read_csv("df_final_web_data_pt_2.csv")
experiment_clients = pd.read_csv("df_final_experiment_clients.csv")

print(demo.shape)
print(web_data_pt_1.shape)
print(web_data_pt_2.shape)
print(experiment_clients.shape)

(70609, 9)
(343141, 5)
(412264, 5)
(70609, 2)

client_id: Every client's unique ID.  
clnt_tenure_yr: Represents how long the client has been with Vanguard, measured in years.  
clnt_tenure_mnth: Further breaks down the client's tenure with Vanguard in months.  
clnt_age: Indicates the age of the client.  
gendr: Specifies the client's gender.  
num_accts: Denotes the number of accounts the client holds with Vanguard.  
bal: Gives the total balance spread across all accounts for a particular client.  
calls_6_mnth: Records the number of times the client reached out over a call in the past six months.  
logons_6_mnth: Reflects the frequency with which the client logged onto Vanguard's platform over the last six months.

In [6]:
demo.head()

,client_id,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth
0,836976,6.0,73.0,60.5,U,2.0,45105.30,6.0,9.0
1,2304905,7.0,94.0,58.0,U,2.0,110860.30,6.0,9.0
2,1439522,5.0,64.0,32.0,U,2.0,52467.79,6.0,9.0
3,1562045,16.0,198.0,49.0,M,2.0,67454.65,3.0,6.0
4,5126305,12.0,145.0,33.0,F,2.0,103671.75,0.0,3.0

client_id: Every client's unique ID.  
visitor_id: A unique ID for each client-device combination.  
visit_id: A unique ID for each web visit/session.  
process_step: Marks each step in the digital process.  
date_time: Timestamp of each web activity.

In [7]:
web_data_pt_1.head()

,client_id,visitor_id,visit_id,process_step,date_time
0,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:27:07
1,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:26:51
2,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:19:22
3,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:19:13
4,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:18:04

In [8]:
web_data_pt_2.head()

,client_id,visitor_id,visit_id,process_step,date_time
0,763412,601952081_10457207388,397475557_40440946728_419634,confirm,2017-06-06 08:56:00
1,6019349,442094451_91531546617,154620534_35331068705_522317,confirm,2017-06-01 11:59:27
2,6019349,442094451_91531546617,154620534_35331068705_522317,step_3,2017-06-01 11:58:48
3,6019349,442094451_91531546617,154620534_35331068705_522317,step_2,2017-06-01 11:58:08
4,6019349,442094451_91531546617,154620534_35331068705_522317,step_1,2017-06-01 11:57:58

client_id: Every client's unique ID.  
variation: Indicates if a client was part of the experiment.

In [9]:
experiment_clients.head()

   client_id Variation
0    9988021      Test
1    8320017      Test
2    4033851   Control
3    1982004      Test
4    9294070   Control

UNIMOS web_data_pt_1 + web_data_pt_2

Tienen mismas columnas asi que con concat llegaria

In [10]:
df_web_union = pd.concat([web_data_pt_1,web_data_pt_2],ignore_index= True)
print(web_data_pt_1.shape)
print(web_data_pt_2.shape)
print(df_web_union.shape)
len(df_web_union) == len(web_data_pt_1) + len(web_data_pt_2) # comprobar si concateno bien

(343141, 5)
(412264, 5)
(755405, 5)

True

Revisar duplicadoss